### PR TITLE
FIX (searchFn)[#101] searchFn callback should only call once when typing in the search bar

### LINKED ISSUE #101: searchFn callback fires twice when typing in search bar
Hi there, I'm having a problem with the `searchFn` callback, apparently each time you type in the search bar the `searchFn` callback gets fired twice. The same thing doesn't seem to happen with `handleKeyDownFn` callback, however the state it returns is a bit late so I can't use it. 

I've created this sandbox [here](https://codesandbox.io/s/searchfn-callback-issue-bfr3u) to demonstrate the issue, try typing in the search bar and then check the console.

### PR DESCRIPTION
**Pull request by pattiereaves**
- Add searchResults array to the component state so that we can store the calculation and prevent it from being executed multiple times.
- Adds example documentation for how to add a custom searchFn.

resolves #101

### CODE REVIEW

**Comment by pattiereaves** [comment]
Would you be willing to [add the hacktoberfest label](https://hacktoberfest.digitalocean.com/faq) to this project?

File: src/index.js [hunk 1]
```diff
@@ -379,6 +382,7 @@ export class Select extends Component {
     });
 
   handleKeyDown = (event) => {
+    console.log({ event });
```
Comment (sanusart) [inline src/index.js:385]: Not needed anymore I believe.

**Review by sanusart — CHANGES_REQUESTED** [review]

**Review by sanusart — APPROVED** [review]
@pattiereaves thank you!
